sudo: required

language: php
php:
  - '7.1.6'

services:
  - docker

branches:
  only:
    - master

# travis runtime environment from here or settings.
env:


# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
  - set -e


# put testing scripts here
script:
  - echo 'script step...'

after_success:
  - echo 'after_success step...'
  - docker --version
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
    export LAST_TAG=$(git describe $(git rev-list --tags --max-count=1));
    docker build -t ${DOCKER_IMAGE} .;
    docker tag ${DOCKER_IMAGE}:latest ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
    docker tag ${DOCKER_IMAGE}:latest ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:${LAST_TAG};
    docker push ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
    docker push ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:${LAST_TAG};
    fi
  - aws ecs register-task-definition --cli-input-json file://.ecs-web.json > ~/tmp/TASK-NEW.JSON
  - export TASK_VERSION=$(cat ~/tmp/TASK-NEW.JSON|python3 -c "import sys, json; print(json.load(sys.stdin)['taskDefinitionArns'][0])")
  - aws ecs update-service --service php-web --task-definition ${TASK_VERSION}
