sudo: required #is required to use docker service in travis

language: php #can be any language, just php for example

# required, but travis uses older version of docker :(
services:
  - docker

env:
  DOCKER_IMAGE: docker-php-example

# put your normal pre-testing installs here
install:
  - echo "***** install step *****"

# put your normal testing scripts here
script:
  - echo '***** script step *****'


before_install:
  - echo 'before_install'


after_success:
  - echo 'after_success'
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
    docker --version;
    pip install --user awscli;
    export PATH=$PATH:$HOME/.local/bin;
    eval $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION});
    docker build -t ${DOCKER_IMAGE} .;
    docker tag ${DOCKER_IMAGE}:latest ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
    echo push to ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
    docker push ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
    fi
